name: Lint
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 5" # weekly on Friday at midnight

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install shellcheck and shfmt
        run: |
          asdf plugin add shellcheck
          asdf plugin add shfmt
          asdf install

      - name: Lint
        run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker://rhysd/actionlint:1.6.23
        with:
          args: -color
