name: Test Mise
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 5" # weekly on Friday at midnight

jobs:
  mise_test:
    name: mise plugin test
    runs-on: macos-latest
    steps:
      - name: Install mise
        uses: jdx/mise-action@v3

      - name: Test plugin
        run: |
          mise exec asdf:https://github.com/younke/asdf-carthage@latest -- carthage version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
